plugins {
    id 'net.neoforged.moddev' version "${moddev_version}"
}

neoForge {
    version = neoforge_version

    runs {
        client { client() }
        server { server() }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet project(':common').sourceSets.main
        }
    }
}

dependencies {
    implementation "dev.architectury:architectury-neoforge:${architectury_api_version}"
    implementation "com.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}"
    implementation "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"
    compileOnly "maven.modrinth:jade:${jade_version}+neoforge"
    runtimeOnly "maven.modrinth:jade:${jade_version}+neoforge"
    compileOnly project(':common')
}

tasks.jar {
    from project(':common').sourceSets.main.output
}
